package com.knowagent.knowledge.infrastructure.vector;

import com.knowagent.common.error.ErrorCode;
import io.milvus.v2.common.DataType;
import io.milvus.v2.common.IndexParam;
import io.milvus.v2.service.collection.request.CreateCollectionReq;
import io.milvus.v2.service.collection.response.DescribeCollectionResp;
import io.milvus.v2.service.index.response.DescribeIndexResp;
import org.junit.jupiter.api.Test;

import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * Locks the startup schema contract: an existing collection whose primary key,
 * dimension, scalar fields, index metric/type or HNSW parameters do not match the
 * fixed contract refuses startup with VECTOR_SCHEMA_MISMATCH - existing data is
 * never dropped or altered.
 */
class MilvusSchemaValidatorTest {

    private static final int DIMENSION = 4;

    @Test
    void aMatchingCollectionPassesValidation() {
        MilvusSchemaValidator.validate(collection(DIMENSION), index(IndexParam.MetricType.COSINE), properties());
    }

    @Test
    void aWrongDimensionIsRejected() {
        assertSchemaMismatch(() -> MilvusSchemaValidator.validate(
                collection(8), index(IndexParam.MetricType.COSINE), properties()));
    }

    @Test
    void aMissingOrWrongPrimaryKeyIsRejected() {
        DescribeCollectionResp noIdPk = collection(DIMENSION, schema -> schema.fieldList.removeIf(
                field -> "id".equals(field.getName()) || Boolean.TRUE.equals(field.getIsPrimaryKey())));
        assertSchemaMismatch(() -> MilvusSchemaValidator.validate(
                noIdPk, index(IndexParam.MetricType.COSINE), properties()));
    }

    @Test
    void autoGeneratedIdsAreRejected() {
        DescribeCollectionResp autoId = collection(DIMENSION, schema -> schema.fieldList.stream()
                .filter(field -> "id".equals(field.getName()))
                .forEach(field -> field.setAutoID(true)));
        assertSchemaMismatch(() -> MilvusSchemaValidator.validate(
                autoId, index(IndexParam.MetricType.COSINE), properties()));
    }

    @Test
    void aMissingVectorFieldOrNonFloatVectorFieldIsRejected() {
        DescribeCollectionResp noVector = collection(DIMENSION, schema -> schema.fieldList.removeIf(
                field -> "embedding".equals(field.getName())));
        assertSchemaMismatch(() -> MilvusSchemaValidator.validate(
                noVector, index(IndexParam.MetricType.COSINE), properties()));

        DescribeCollectionResp wrongType = collection(DIMENSION, schema -> schema.fieldList.stream()
                .filter(field -> "embedding".equals(field.getName()))
                .forEach(field -> field.setDataType(DataType.BinaryVector)));
        assertSchemaMismatch(() -> MilvusSchemaValidator.validate(
                wrongType, index(IndexParam.MetricType.COSINE), properties()));
    }

    @Test
    void aMissingScalarFieldIsRejected() {
        DescribeCollectionResp noTenant = collection(DIMENSION, schema -> schema.fieldList.removeIf(
                field -> "tenant_id".equals(field.getName())));
        assertSchemaMismatch(() -> MilvusSchemaValidator.validate(
                noTenant, index(IndexParam.MetricType.COSINE), properties()));
    }

    @Test
    void aNonCosineIndexIsRejected() {
        assertSchemaMismatch(() -> MilvusSchemaValidator.validate(
                collection(DIMENSION), index(IndexParam.MetricType.L2), properties()));
    }

    @Test
    void anEmptyIndexListIsRejected() {
        DescribeIndexResp empty = DescribeIndexResp.builder().indexDescriptions(List.of()).build();
        assertSchemaMismatch(() -> MilvusSchemaValidator.validate(collection(DIMENSION), empty, properties()));
    }

    @Test
    void aWrongIndexTypeOrHnswParametersAreRejected() {
        assertSchemaMismatch(() -> MilvusSchemaValidator.validate(collection(DIMENSION),
                index(IndexParam.MetricType.COSINE, IndexParam.IndexType.FLAT,
                        java.util.Map.of()), properties()));
        assertSchemaMismatch(() -> MilvusSchemaValidator.validate(collection(DIMENSION),
                index(IndexParam.MetricType.COSINE, IndexParam.IndexType.HNSW,
                        java.util.Map.of("M", "32", "efConstruction", "64")), properties()));
    }

    private static void assertSchemaMismatch(Runnable call) {
        assertThatThrownBy(call::run)
                .isInstanceOf(VectorStoreException.class)
                .satisfies(e -> assertThat(((VectorStoreException) e).errorCode())
                        .isEqualTo(ErrorCode.VECTOR_SCHEMA_MISMATCH));
    }

    /** Mutable carrier so tests can tweak the schema before validation. */
    private static final class SchemaCarrier {
        final List<CreateCollectionReq.FieldSchema> fieldList;

        SchemaCarrier(List<CreateCollectionReq.FieldSchema> fieldList) {
            this.fieldList = fieldList;
        }
    }

    private static DescribeCollectionResp collection(int dimension,
                                                     java.util.function.Consumer<SchemaCarrier> tweak) {
        CreateCollectionReq.FieldSchema id = CreateCollectionReq.FieldSchema.builder()
                .name("id").dataType(DataType.VarChar).maxLength(64).isPrimaryKey(true).autoID(false).build();
        CreateCollectionReq.FieldSchema tenant = CreateCollectionReq.FieldSchema.builder()
                .name("tenant_id").dataType(DataType.VarChar).maxLength(64).build();
        CreateCollectionReq.FieldSchema kb = CreateCollectionReq.FieldSchema.builder()
                .name("knowledge_base_id").dataType(DataType.VarChar).maxLength(64).build();
        CreateCollectionReq.FieldSchema file = CreateCollectionReq.FieldSchema.builder()
                .name("file_id").dataType(DataType.VarChar).maxLength(64).build();
        CreateCollectionReq.FieldSchema chunk = CreateCollectionReq.FieldSchema.builder()
                .name("chunk_id").dataType(DataType.VarChar).maxLength(64).build();
        CreateCollectionReq.FieldSchema spec = CreateCollectionReq.FieldSchema.builder()
                .name("embedding_model_spec").dataType(DataType.VarChar).maxLength(512).build();
        CreateCollectionReq.FieldSchema embedding = CreateCollectionReq.FieldSchema.builder()
                .name("embedding").dataType(DataType.FloatVector).dimension(dimension).build();
        SchemaCarrier carrier = new SchemaCarrier(new java.util.ArrayList<>(List.of(id, tenant, kb, file, chunk, spec, embedding)));
        tweak.accept(carrier);
        CreateCollectionReq.CollectionSchema schema = CreateCollectionReq.CollectionSchema.builder()
                .fieldSchemaList(carrier.fieldList)
                .build();
        return DescribeCollectionResp.builder()
                .collectionName("knowledge_chunks")
                .primaryFieldName("id")
                .collectionSchema(schema)
                .build();
    }

    private static DescribeCollectionResp collection(int dimension) {
        return collection(dimension, ignored -> {
        });
    }

    private static DescribeIndexResp index(IndexParam.MetricType metricType) {
        return index(metricType, IndexParam.IndexType.HNSW,
                java.util.Map.of("M", "16", "efConstruction", "64"));
    }

    private static DescribeIndexResp index(IndexParam.MetricType metricType, IndexParam.IndexType indexType,
                                           java.util.Map<String, String> params) {
        DescribeIndexResp.IndexDesc indexDesc = DescribeIndexResp.IndexDesc.builder()
                .fieldName("embedding")
                .indexName("embedding_index")
                .indexType(indexType)
                .metricType(metricType)
                .extraParams(params)
                .build();
        return DescribeIndexResp.builder().indexDescriptions(List.of(indexDesc)).build();
    }

    private static MilvusVectorProperties properties() {
        return new MilvusVectorProperties(
                "http://localhost:19530", null, null, null, null, "knowledge_chunks", DIMENSION, "HNSW",
                16, 64, 64, java.time.Duration.ofSeconds(5), java.time.Duration.ofSeconds(30),
                java.time.Duration.ofSeconds(10), java.time.Duration.ofSeconds(30),
                java.time.Duration.ofSeconds(30), java.time.Duration.ofSeconds(120));
    }
}
